version: '3'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./:/app/server/labq
    ports:
      - 8000:8000
    env_file:
      - ./LabQ/my_settings.py
